name: dotnet build (release)

on:
  workflow_dispatch:

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  DOTNET_NOLOGO: true

jobs:
  build:
    name: Build (Release)
    needs: [.github/workflows/dotnet-config]
    runs-on: ${{ needs.dotnet-config.outputs.runner }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ needs.dotnet-config.outputs.dotnet-version }}

    - name: Load dependencies cache
      uses: actions/cache@v3
      with:
        path: .nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget

    - name: Install dependencies
      run: dotnet restore --configfile Nuget.config

    - name: Build release
      run: dotnet build --nologo --no-restore --configuration Release

    - name: Upload release artifact
      uses: actions/upload-artifact@v4
      with:
        name: release
        path: ${{ needs.dotnet-config.outputs.bin-release }}